l3file("https://www.googletagmanager.com/gtag/js?id=G-GC3PR9DQEJ", "js")
l3file("https://cdn.statically.io/gh/hamdaniazzah/hamdaniazzah.github.io/master/l3/css/gen_3.css", "css")
l3file("https://cdn.ampproject.org/v0.js", "js")
l3file("https://cdn.statically.io/gh/hamdaniazzah/hamdaniazzah.github.io/master/l3/js/gen_4.js", "js")
l3file("https://cdnjs.cloudflare.com/ajax/libs/lazysizes/5.2.2/lazysizes.min.js", "js")
